language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - ./vendor/bin/phpunit --verbose tests/MockTest
  - ./vendor/bin/phpunit --verbose tests/SerializeTest

matrix:
  allow_failures:
    - php: hhvm
    - php: 5.4
    - php: 5.5
  fast_finish: true
